PREFIX odrl: <http://www.w3.org/ns/odrl/2/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX tosl: <https://w3id.org/tosl/>

SELECT (COUNT(DISTINCT ?prohibition) AS ?totalProhibitions)
WHERE {
  ?prohibition a odrl:Prohibition .
}